// Package swapv2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package swapv2

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for BuildGetParamsMode.
const (
	Fast BuildGetParamsMode = "fast"
)

// AccountMeta defines model for AccountMeta.
type AccountMeta struct {
	IsSigner   bool   `json:"isSigner"`
	IsWritable bool   `json:"isWritable"`
	Pubkey     string `json:"pubkey"`
}

// BlockhashFetchedAt Server timestamp at which the blockhash was fetched.
type BlockhashFetchedAt struct {
	NanosSinceEpoch *int64 `json:"nanos_since_epoch,omitempty"`
	SecsSinceEpoch  *int64 `json:"secs_since_epoch,omitempty"`
}

// BlockhashWithMetadata defines model for BlockhashWithMetadata.
type BlockhashWithMetadata struct {
	Blockhash *[]int `json:"blockhash,omitempty"`

	// FetchedAt Server timestamp at which the blockhash was fetched.
	FetchedAt            *BlockhashFetchedAt `json:"fetchedAt,omitempty"`
	LastValidBlockHeight *int                `json:"lastValidBlockHeight,omitempty"`
}

// BuildResponse defines model for BuildResponse.
type BuildResponse struct {
	// AddressesByLookupTableAddress Address lookup table mappings for v0 transactions
	AddressesByLookupTableAddress *map[string][]string   `json:"addressesByLookupTableAddress,omitempty"`
	BlockhashWithMetadata         *BlockhashWithMetadata `json:"blockhashWithMetadata,omitempty"`
	CleanupInstruction            *Instruction           `json:"cleanupInstruction,omitempty"`

	// ComputeBudgetInstructions Compute unit price instruction (does not include compute unit limit)
	ComputeBudgetInstructions *[]Instruction `json:"computeBudgetInstructions,omitempty"`
	InAmount                  *string        `json:"inAmount,omitempty"`
	InputMint                 *string        `json:"inputMint,omitempty"`

	// OtherAmountThreshold Minimum output amount after slippage
	OtherAmountThreshold *string            `json:"otherAmountThreshold,omitempty"`
	OtherInstructions    *[]Instruction     `json:"otherInstructions,omitempty"`
	OutAmount            *string            `json:"outAmount,omitempty"`
	OutputMint           *string            `json:"outputMint,omitempty"`
	RoutePlan            *[]RoutePlanStepV2 `json:"routePlan,omitempty"`

	// SetupInstructions Pre-swap setup instructions (e.g. create ATAs)
	SetupInstructions *[]Instruction `json:"setupInstructions,omitempty"`
	SlippageBps       *float32       `json:"slippageBps,omitempty"`
	SwapInstruction   *Instruction   `json:"swapInstruction,omitempty"`
	SwapMode          *string        `json:"swapMode,omitempty"`
	TipInstruction    *Instruction   `json:"tipInstruction,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code  *int    `json:"code,omitempty"`
	Error *string `json:"error,omitempty"`
}

// Instruction defines model for Instruction.
type Instruction struct {
	Accounts  []AccountMeta `json:"accounts"`
	Data      string        `json:"data"`
	ProgramId string        `json:"programId"`
}

// RoutePlanStepV2 defines model for RoutePlanStepV2.
type RoutePlanStepV2 struct {
	Bps      *float32   `json:"bps,omitempty"`
	Percent  *float32   `json:"percent,omitempty"`
	SwapInfo SwapInfoV2 `json:"swapInfo"`
	UsdValue *float32   `json:"usdValue,omitempty"`
}

// SwapInfoV2 defines model for SwapInfoV2.
type SwapInfoV2 struct {
	AmmKey     string  `json:"ammKey"`
	InAmount   string  `json:"inAmount"`
	InputMint  string  `json:"inputMint"`
	Label      *string `json:"label,omitempty"`
	OutAmount  string  `json:"outAmount"`
	OutputMint string  `json:"outputMint"`
}

// BuildGetParams defines parameters for BuildGet.
type BuildGetParams struct {
	// InputMint The mint address of the input token
	InputMint string `form:"inputMint" json:"inputMint"`

	// OutputMint The mint address of the output token
	OutputMint string `form:"outputMint" json:"outputMint"`

	// Amount The amount to swap in the smallest unit of the input token
	Amount string `form:"amount" json:"amount"`

	// Taker Public key of the user initiating the swap
	Taker string `form:"taker" json:"taker"`

	// SlippageBps Slippage tolerance in basis points, as a number (e.g. "50"), or "rtse" for real-time slippage estimation. Defaults to 50.
	SlippageBps *string `form:"slippageBps,omitempty" json:"slippageBps,omitempty"`

	// Mode Quoting mode. "fast" trades quote optimality for reduced latency.
	Mode *BuildGetParamsMode `form:"mode,omitempty" json:"mode,omitempty"`

	// Dexes Comma-separated list of DEXes to restrict routing to. Mutually exclusive with excludeDexes.
	Dexes *string `form:"dexes,omitempty" json:"dexes,omitempty"`

	// ExcludeDexes Comma-separated list of DEXes to exclude. Mutually exclusive with dexes.
	ExcludeDexes *string `form:"excludeDexes,omitempty" json:"excludeDexes,omitempty"`

	// PlatformFeeBps Platform fee in basis points. If positive, feeAccount is required.
	PlatformFeeBps *int `form:"platformFeeBps,omitempty" json:"platformFeeBps,omitempty"`

	// FeeAccount Token account to collect platform fees. Required if platformFeeBps is positive.
	FeeAccount *string `form:"feeAccount,omitempty" json:"feeAccount,omitempty"`

	// MaxAccounts Maximum number of accounts for the swap route. Defaults to 64.
	MaxAccounts *int `form:"maxAccounts,omitempty" json:"maxAccounts,omitempty"`

	// Payer Account that pays transaction fees and rent. Defaults to taker when not passed in.
	Payer *string `form:"payer,omitempty" json:"payer,omitempty"`

	// WrapAndUnwrapSol Whether to wrap/unwrap SOL. Defaults to true.
	WrapAndUnwrapSol *bool `form:"wrapAndUnwrapSol,omitempty" json:"wrapAndUnwrapSol,omitempty"`

	// DestinationTokenAccount SPL token account to receive output tokens. Mutually exclusive with nativeDestinationAccount.
	DestinationTokenAccount *string `form:"destinationTokenAccount,omitempty" json:"destinationTokenAccount,omitempty"`

	// NativeDestinationAccount Native SOL account to receive output. Mutually exclusive with destinationTokenAccount.
	NativeDestinationAccount *string `form:"nativeDestinationAccount,omitempty" json:"nativeDestinationAccount,omitempty"`

	// BlockhashSlotsToExpiry Number of slots until the blockhash expires. Defaults to 150.
	BlockhashSlotsToExpiry *int `form:"blockhashSlotsToExpiry,omitempty" json:"blockhashSlotsToExpiry,omitempty"`

	// TipAmount SOL tip amount in lamports. Adds a tip instruction for use with /submit.
	TipAmount *string `form:"tipAmount,omitempty" json:"tipAmount,omitempty"`

	// ComputeUnitPricePercentile Percentile of compute unit price to use, as a number (0-10000 basis points), or a named level: "medium" (25th), "high" (50th), "veryHigh" (75th).
	ComputeUnitPricePercentile *string `form:"computeUnitPricePercentile,omitempty" json:"computeUnitPricePercentile,omitempty"`
}

// BuildGetParamsMode defines parameters for BuildGet.
type BuildGetParamsMode string

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// BuildGet request
	BuildGet(ctx context.Context, params *BuildGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ProgramIdToLabelGet request
	ProgramIdToLabelGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) BuildGet(ctx context.Context, params *BuildGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBuildGetRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ProgramIdToLabelGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewProgramIdToLabelGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewBuildGetRequest generates requests for BuildGet
func NewBuildGetRequest(server string, params *BuildGetParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/build")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "inputMint", runtime.ParamLocationQuery, params.InputMint); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "outputMint", runtime.ParamLocationQuery, params.OutputMint); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "amount", runtime.ParamLocationQuery, params.Amount); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "taker", runtime.ParamLocationQuery, params.Taker); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.SlippageBps != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "slippageBps", runtime.ParamLocationQuery, *params.SlippageBps); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Mode != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "mode", runtime.ParamLocationQuery, *params.Mode); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Dexes != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "dexes", runtime.ParamLocationQuery, *params.Dexes); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ExcludeDexes != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "excludeDexes", runtime.ParamLocationQuery, *params.ExcludeDexes); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PlatformFeeBps != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "platformFeeBps", runtime.ParamLocationQuery, *params.PlatformFeeBps); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.FeeAccount != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "feeAccount", runtime.ParamLocationQuery, *params.FeeAccount); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.MaxAccounts != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "maxAccounts", runtime.ParamLocationQuery, *params.MaxAccounts); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Payer != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "payer", runtime.ParamLocationQuery, *params.Payer); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.WrapAndUnwrapSol != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "wrapAndUnwrapSol", runtime.ParamLocationQuery, *params.WrapAndUnwrapSol); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.DestinationTokenAccount != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "destinationTokenAccount", runtime.ParamLocationQuery, *params.DestinationTokenAccount); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.NativeDestinationAccount != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "nativeDestinationAccount", runtime.ParamLocationQuery, *params.NativeDestinationAccount); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.BlockhashSlotsToExpiry != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "blockhashSlotsToExpiry", runtime.ParamLocationQuery, *params.BlockhashSlotsToExpiry); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.TipAmount != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "tipAmount", runtime.ParamLocationQuery, *params.TipAmount); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ComputeUnitPricePercentile != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "computeUnitPricePercentile", runtime.ParamLocationQuery, *params.ComputeUnitPricePercentile); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewProgramIdToLabelGetRequest generates requests for ProgramIdToLabelGet
func NewProgramIdToLabelGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/program-id-to-label")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// BuildGetWithResponse request
	BuildGetWithResponse(ctx context.Context, params *BuildGetParams, reqEditors ...RequestEditorFn) (*BuildGetResponse, error)

	// ProgramIdToLabelGetWithResponse request
	ProgramIdToLabelGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ProgramIdToLabelGetResponse, error)
}

type BuildGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BuildResponse
	JSON400      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r BuildGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BuildGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ProgramIdToLabelGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *map[string]string
}

// Status returns HTTPResponse.Status
func (r ProgramIdToLabelGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ProgramIdToLabelGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// BuildGetWithResponse request returning *BuildGetResponse
func (c *ClientWithResponses) BuildGetWithResponse(ctx context.Context, params *BuildGetParams, reqEditors ...RequestEditorFn) (*BuildGetResponse, error) {
	rsp, err := c.BuildGet(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBuildGetResponse(rsp)
}

// ProgramIdToLabelGetWithResponse request returning *ProgramIdToLabelGetResponse
func (c *ClientWithResponses) ProgramIdToLabelGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ProgramIdToLabelGetResponse, error) {
	rsp, err := c.ProgramIdToLabelGet(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseProgramIdToLabelGetResponse(rsp)
}

// ParseBuildGetResponse parses an HTTP response from a BuildGetWithResponse call
func ParseBuildGetResponse(rsp *http.Response) (*BuildGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BuildGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BuildResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseProgramIdToLabelGetResponse parses an HTTP response from a ProgramIdToLabelGetWithResponse call
func ParseProgramIdToLabelGetResponse(rsp *http.Response) (*ProgramIdToLabelGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ProgramIdToLabelGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]string
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
