// Package jupiter provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package jupiter

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for BuildGetParamsComputeUnitPricePercentile.
const (
	BuildGetParamsComputeUnitPricePercentileHigh     BuildGetParamsComputeUnitPricePercentile = "high"
	BuildGetParamsComputeUnitPricePercentileMedium   BuildGetParamsComputeUnitPricePercentile = "medium"
	BuildGetParamsComputeUnitPricePercentileVeryHigh BuildGetParamsComputeUnitPricePercentile = "veryHigh"
)

// Defines values for BuildGetParamsMode.
const (
	BuildGetParamsModeFast BuildGetParamsMode = "fast"
)

// Defines values for BuildGetParamsSlippageBps.
const (
	BuildGetParamsSlippageBpsRtse BuildGetParamsSlippageBps = "rtse"
)

// BlockhashWithMetadata defines model for BlockhashWithMetadata.
type BlockhashWithMetadata struct {
	Blockhash            []int               `json:"blockhash,omitempty"`
	LastValidBlockHeight *int                `json:"lastValidBlockHeight,omitempty"`
	FetchedAt            *BlockhashFetchedAt `json:"fetchedAt,omitempty"`
}

// BlockhashFetchedAt is the server timestamp at which the blockhash was fetched.
type BlockhashFetchedAt struct {
	SecsSinceEpoch  *int64 `json:"secs_since_epoch,omitempty"`
	NanosSinceEpoch *int64 `json:"nanos_since_epoch,omitempty"`
}

// BuildResponse defines model for BuildResponse.
type BuildResponse struct {
	AddressesByLookupTableAddress *map[string][]string   `json:"addressesByLookupTableAddress,omitempty"`
	BlockhashWithMetadata         *BlockhashWithMetadata `json:"blockhashWithMetadata,omitempty"`
	CleanupInstruction            *Instruction           `json:"cleanupInstruction,omitempty"`

	// ComputeBudgetInstructions Compute unit price instruction (does not include compute unit limit)
	ComputeBudgetInstructions *[]Instruction `json:"computeBudgetInstructions,omitempty"`
	InAmount                  *string        `json:"inAmount,omitempty"`
	InputMint                 *string        `json:"inputMint,omitempty"`
	OutAmount                 *string        `json:"outAmount,omitempty"`

	// OtherAmountThreshold Minimum output amount after slippage
	OtherAmountThreshold *string            `json:"otherAmountThreshold,omitempty"`
	PriceImpactPct       *string            `json:"priceImpactPct,omitempty"`
	OtherInstructions    *[]Instruction     `json:"otherInstructions,omitempty"`
	OutputMint           *string            `json:"outputMint,omitempty"`
	RoutePlan            *[]RoutePlanStepV2 `json:"routePlan,omitempty"`

	// SetupInstructions Pre-swap setup instructions (e.g. create ATAs)
	SetupInstructions *[]Instruction `json:"setupInstructions,omitempty"`
	SlippageBps       *float32       `json:"slippageBps,omitempty"`
	SwapInstruction   *Instruction   `json:"swapInstruction,omitempty"`
	SwapMode          *string        `json:"swapMode,omitempty"`
	TipInstruction    *Instruction   `json:"tipInstruction,omitempty"`
}

// RoutePlanStepV2 defines model for RoutePlanStepV2.
type RoutePlanStepV2 struct {
	Bps      *float64   `json:"bps,omitempty"`
	Percent  *float64   `json:"percent,omitempty"`
	SwapInfo SwapInfoV2 `json:"swapInfo"`
	UsdValue *float64   `json:"usdValue,omitempty"`
}

// SwapInfoV2 defines model for SwapInfoV2.
type SwapInfoV2 struct {
	AmmKey     string  `json:"ammKey"`
	InAmount   string  `json:"inAmount"`
	InputMint  string  `json:"inputMint"`
	Label      *string `json:"label,omitempty"`
	OutAmount  string  `json:"outAmount"`
	OutputMint string  `json:"outputMint"`
}

// BuildGetParamsComputeUnitPricePercentile defines parameters for BuildGet.
type BuildGetParamsComputeUnitPricePercentile string

// BuildGetParamsMode defines parameters for BuildGet.
type BuildGetParamsMode string

// BuildGetParamsSlippageBps defines parameters for BuildGet.
type BuildGetParamsSlippageBps string

// BuildGetParams defines parameters for BuildGet.
type BuildGetParams struct {
	// InputMint The mint address of the input token
	InputMint string `form:"inputMint" json:"inputMint"`

	// OutputMint The mint address of the output token
	OutputMint string `form:"outputMint" json:"outputMint"`

	// Amount The amount to swap in the smallest unit of the input token
	Amount string `form:"amount" json:"amount"`

	// Taker Public key of the user initiating the swap
	Taker string `form:"taker" json:"taker"`

	// SlippageBps Slippage tolerance in basis points. Defaults to 50.
	SlippageBps *BuildGetParamsSlippageBps `form:"slippageBps,omitempty" json:"slippageBps,omitempty"`

	// SlippageBpsNum Slippage tolerance as a numeric value.
	SlippageBpsNum *int `form:"slippageBps,omitempty" json:"slippageBpsNum,omitempty"`

	// Mode Quoting mode. "fast" trades quote optimality for reduced latency.
	Mode *BuildGetParamsMode `form:"mode,omitempty" json:"mode,omitempty"`

	// Dexes Comma-separated list of DEXes to restrict routing to. Mutually exclusive with ExcludeDexes.
	Dexes *string `form:"dexes,omitempty" json:"dexes,omitempty"`

	// ExcludeDexes Comma-separated list of DEXes to exclude. Mutually exclusive with Dexes.
	ExcludeDexes *string `form:"excludeDexes,omitempty" json:"excludeDexes,omitempty"`

	// PlatformFeeBps Platform fee in basis points. If positive, FeeAccount is required.
	PlatformFeeBps *int `form:"platformFeeBps,omitempty" json:"platformFeeBps,omitempty"`

	// FeeAccount Token account to collect platform fees. Required if PlatformFeeBps is positive.
	FeeAccount *string `form:"feeAccount,omitempty" json:"feeAccount,omitempty"`

	// MaxAccounts Maximum number of accounts for the swap route. Defaults to 64.
	MaxAccounts *int `form:"maxAccounts,omitempty" json:"maxAccounts,omitempty"`

	// Payer Account that pays transaction fees and rent. Defaults to Taker.
	Payer *string `form:"payer,omitempty" json:"payer,omitempty"`

	// WrapAndUnwrapSol Whether to wrap/unwrap SOL. Defaults to true.
	WrapAndUnwrapSol *bool `form:"wrapAndUnwrapSol,omitempty" json:"wrapAndUnwrapSol,omitempty"`

	// DestinationTokenAccount SPL token account to receive output tokens. Mutually exclusive with NativeDestinationAccount.
	DestinationTokenAccount *string `form:"destinationTokenAccount,omitempty" json:"destinationTokenAccount,omitempty"`

	// NativeDestinationAccount Native SOL account to receive output. Mutually exclusive with DestinationTokenAccount.
	NativeDestinationAccount *string `form:"nativeDestinationAccount,omitempty" json:"nativeDestinationAccount,omitempty"`

	// BlockhashSlotsToExpiry Number of slots until the blockhash expires. Defaults to 150.
	BlockhashSlotsToExpiry *int `form:"blockhashSlotsToExpiry,omitempty" json:"blockhashSlotsToExpiry,omitempty"`

	// TipAmount SOL tip amount in lamports.
	TipAmount *string `form:"tipAmount,omitempty" json:"tipAmount,omitempty"`

	// ComputeUnitPricePercentile Named percentile level or basis points value.
	ComputeUnitPricePercentile *BuildGetParamsComputeUnitPricePercentile `form:"computeUnitPricePercentile,omitempty" json:"computeUnitPricePercentile,omitempty"`

	// ComputeUnitPricePercentileNum Numeric compute unit price percentile (0-10000).
	ComputeUnitPricePercentileNum *int `form:"computeUnitPricePercentile,omitempty" json:"computeUnitPricePercentileNum,omitempty"`
}

// NewBuildGetRequest generates requests for BuildGet
func NewBuildGetRequest(server string, params *BuildGetParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/build")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "inputMint", runtime.ParamLocationQuery, params.InputMint); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "outputMint", runtime.ParamLocationQuery, params.OutputMint); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "amount", runtime.ParamLocationQuery, params.Amount); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "taker", runtime.ParamLocationQuery, params.Taker); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.SlippageBps != nil {
			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "slippageBps", runtime.ParamLocationQuery, *params.SlippageBps); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		} else if params.SlippageBpsNum != nil {
			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "slippageBps", runtime.ParamLocationQuery, *params.SlippageBpsNum); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}

		if params.Mode != nil {
			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "mode", runtime.ParamLocationQuery, *params.Mode); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}

		if params.Dexes != nil {
			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "dexes", runtime.ParamLocationQuery, *params.Dexes); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}

		if params.ExcludeDexes != nil {
			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "excludeDexes", runtime.ParamLocationQuery, *params.ExcludeDexes); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}

		if params.PlatformFeeBps != nil {
			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "platformFeeBps", runtime.ParamLocationQuery, *params.PlatformFeeBps); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}

		if params.FeeAccount != nil {
			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "feeAccount", runtime.ParamLocationQuery, *params.FeeAccount); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}

		if params.MaxAccounts != nil {
			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "maxAccounts", runtime.ParamLocationQuery, *params.MaxAccounts); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}

		if params.Payer != nil {
			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "payer", runtime.ParamLocationQuery, *params.Payer); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}

		if params.WrapAndUnwrapSol != nil {
			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "wrapAndUnwrapSol", runtime.ParamLocationQuery, *params.WrapAndUnwrapSol); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}

		if params.DestinationTokenAccount != nil {
			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "destinationTokenAccount", runtime.ParamLocationQuery, *params.DestinationTokenAccount); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}

		if params.NativeDestinationAccount != nil {
			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "nativeDestinationAccount", runtime.ParamLocationQuery, *params.NativeDestinationAccount); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}

		if params.BlockhashSlotsToExpiry != nil {
			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "blockhashSlotsToExpiry", runtime.ParamLocationQuery, *params.BlockhashSlotsToExpiry); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}

		if params.TipAmount != nil {
			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "tipAmount", runtime.ParamLocationQuery, *params.TipAmount); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}

		if params.ComputeUnitPricePercentile != nil {
			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "computeUnitPricePercentile", runtime.ParamLocationQuery, *params.ComputeUnitPricePercentile); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		} else if params.ComputeUnitPricePercentileNum != nil {
			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "computeUnitPricePercentile", runtime.ParamLocationQuery, *params.ComputeUnitPricePercentileNum); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) BuildGet(ctx context.Context, params *BuildGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBuildGetRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

type BuildGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BuildResponse
}

// Status returns HTTPResponse.Status
func (r BuildGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BuildGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ParseBuildGetResponse parses an HTTP response from a BuildGetWithResponse call
func ParseBuildGetResponse(rsp *http.Response) (*BuildGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BuildGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BuildResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest
	}

	return response, nil
}

// BuildGetWithResponse request returning *BuildGetResponse
func (c *ClientWithResponses) BuildGetWithResponse(ctx context.Context, params *BuildGetParams, reqEditors ...RequestEditorFn) (*BuildGetResponse, error) {
	client, ok := c.ClientInterface.(*Client)
	if !ok {
		return nil, fmt.Errorf("ClientWithResponses does not wrap a *Client")
	}
	rsp, err := client.BuildGet(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBuildGetResponse(rsp)
}
